---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: pr-argocd-previews-poc-1
  namespace: argocd
spec:
  destination:
    namespace: previews
    server: https://kubernetes.default.svc
  project: previews
  source:
    helm:
      values: |
        image:
          tag: "latest"
        ingress:
          host: "pr-argocd-previews-poc-1.63db-145-224-105-156.eu.ngrok.io"
      version: v3
    path: helm
    repoURL: https://github.com/TomasRebro/argocd-previews-poc.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
