---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: pr-argocd-previews-poc-3
  namespace: argocd
spec:
  destination:
    namespace: pr-argocd-previews-poc-3
    server: https://kubernetes.default.svc
  project: previews
  source:
    helm:
      values: |
        image:
          tag: "latest"
        ingress:
          host: "pr-argocd-previews-poc-3.127.0.0.1.nip.io"
      version: v3
    path: project-templates
    repoURL: https://github.com/TomasRebro/argocd-previews-poc.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
